### ISSUE TITLE
concat base IRI with substring of id property

### ISSUE THREAD

**Issue by smierz** [RMLio/rmlmapper-java#105]
Hello, 
it's only my first time using yarrrml and I'm trying to build the IRI of a subject which should consist of the base+part of the id property, but unfortunately I can't seem to get the hang of functions really.

So for example the id property could be something like: "id": "https://orcid.org/0000-0001-9924-9153"
and I would like to extract only the last part consisting of all the numbers.

So far what I came up with is:
```
    s: 
      function: grel:array_join
      parameters:
        - [grel:p_array_a, base]
        - parameter: grel:p_array_a
          value:
            function: grel:string_find
            parameters:
              - [grel:valueParam, $(id)]
              - [grel:param_regex, "\d{4}-\d{4}-\d{4}-\d{4}"]
```

but Matey is not happy and gives me no output :(

**Comment by pheyvaer** [comment]
Hi @smierz,

Could you provide an sample of the input data and the rest of your YARRRML? That way we can easier determine where it's going wrong.

**Comment by smierz** [comment]
json input:
```
{
    "person": {
      "name": "Test User",
      "id": "https://orcid.org/0000-0005-3029-1234"
    }
}
```

the yarrml is supposed to take the number combination of the id-URl and use base+number combination as new URI for the subject:

```
base: http://example.com/
prefixes:
  foaf: http://xmlns.com/foaf/0.1/
  grel: http://users.ugent.be/~bjdmeest/function/grel.ttl#

mappings:

  person:
    sources:
      - ['data.json~jsonpath', '$.person']
    s: 
      function: grel:array_join
      parameters:
        - [grel:p_array_a, base]
        - parameter: grel:p_array_a
          value:
            function: grel:string_find
            parameters:
              - [grel:valueParam, $(id)]
              - [grel:param_regex, "\d{4}-\d{4}-\d{4}-\d{4}"]
    po:
      - [a, foaf:Person]
```
