### ISSUE TITLE
CSV handling not working when empty column header encountered

### ISSUE THREAD

**Issue by mvanbrab** [RMLio/rmlmapper-java#124]
Handling this issue.csv
```
ColumnA,,ColumnC
s,,o
```
with this YARRRML for example
```
prefixes:
  ex: "http://example.com/"

mappings:
  test:
    sources:
      - ['issue.csv~csv']
    s: ex:$(ColumnA)
    po:
      - [ex:something, ex:$(ColumnC)~iri]
```
gives an empty output.
