### ISSUE TITLE
Parse XML with namespace

### ISSUE THREAD

**Issue by florent-andre** [RMLio/rmlmapper-java#132]
Hello,
First, thanks for this promising tool set. And I hope I send the question on the good canal and repository. 

I try to map an xml with namespaces for nodes (an `xsd` type file).
When I remove the namespaces from my source file, the test triples are generated. 
But when I restaure namespace in the xml file and add xsd: ns to xpath, I get an empty set of triples. 

As I find no example of "xml with namespace" parsing, I ask myself how I can do that.

Here is the example I try to tackle, this can be added to mattey.
Thanks for you help, 
regards
* source xml file with ns
```xml
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:hropen="https://hropenstandards.org/schema/xml/" targetNamespace="https://hropenstandards.org/schema/xml/" version="4.3.0" id="PersonType" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:include schemaLocation="PersonPhysicalInclusion.xsd" />
  <xsd:include schemaLocation="PersonLegalInclusion.xsd" />
  <xsd:include schemaLocation="../profile/PersonProfileInclusion.xsd" />
  <xsd:include schemaLocation="PersonBaseType.xsd" />
  <xsd:complexType name="PersonType">
    <xsd:annotation>
      <xsd:documentation>A schema that represents all of the information of a person.</xsd:documentation>
    </xsd:annotation>
    <xsd:all>
      <xsd:element minOccurs="0" maxOccurs="1" name="legalId" type="hropen:IdentifierType">
        <xsd:annotation>
          <xsd:documentation>The legal identifier of a person. The issuer is most likely a country or state.</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
    </xsd:all>
  </xsd:complexType>
</xsd:schema>
```
* yarrrml configuration
```yaml
prefixes:
  rml: 'http://semweb.mmlab.be/ns/rml#'
  rr: 'http://www.w3.org/ns/r2rml#'
  ql: 'http://semweb.mmlab.be/ns/ql#'
  rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
  "": 'http://example.org/rules/'
  schema: 'http://schema.org/'
  dbo: 'http://dbpedia.org/ontology/'
  test: 'https://test.fr/mm'
  fno: 'https://w3id.org/function/ontology#'
  fnoi: 'https://w3id.org/function/vocabulary/implementation#'
  fnom: 'https://w3id.org/function/vocabulary/mapping#'
  fnml: 'http://semweb.mmlab.be/ns/fnml#'
  grel: 'http://users.ugent.be/~bjdmeest/function/grel.ttl#'
  xsd: 'http://www.w3.org/2001/XMLSchema'
mappings:
  mapping0:
    sources:
      - [Supergirl.xml~xpath, /xsd:schema/xsd:complexType/xsd:all/xsd:element]
    s: 'http://example.org/character/$(@name)'
    po:
      - [a, 'schema:PersonTEST~iri']
      - ['schema:TARGET', $(@type)]
      - ['schema:DESCR', $(xsd:annotation/xsd:documentation)]
      - ['dbo:SHACL', $(@minOccurs)]
```
