### ISSUE TITLE
No mapping was found for grel:date_toDate

### ISSUE THREAD

**Issue by andrecastro0o** [RMLio/rmlmapper-java#142]
Hi,
I am playing a bit with RMLmapper and Yarrrml and tried to convert a date string to a xsd:datetime using grel:date_toDate function. However when I run the following error is returned 

> 09:36:54.593 [main] ERROR be.ugent.rml.cli.Main               .main(338) - No mapping was found for the function with IRI <http://users.ugent.be/~bjdmeest/function/grel.ttl#date_toDate> in the function descriptions.

I am using 
* `rmlio/rmlmapper-java:latest` and `rmlio/yarrrml-parser:latest` (1.3.0) docker images
* The input file: [episodes.json](https://rml.io/yarrrml/tutorial/getting-started/data/episodes.json)
* and the following mapping input
```yaml
prefixes:
  ex: http://www.example.com/
  grel: http://users.ugent.be/~bjdmeest/function/grel.ttl# 
  schema: http://schema.org/
  xsd: http://www.w3.org/2001/XMLSchema/

mappings:
  episode:
    sources:
      - [episodes.json~jsonpath, "$.episodes[*]"]
    s: ex:episode_$(number)
    po:
      - [a, schema:Episode]
      - p: schema:name
        o: 
          value: $(title)
          language: en
      - p: schema:datePublished
        o: 
          function: grel:date_toDate
          parameters: 
            - [grel:valueParameter, $(airdate)]
            - [grel:param_string_pattern, "dd/MM/yyyy"]
```

Despite `grel:date_toDate` being in 
https://github.com/RMLio/rmlmapper-java/blob/d0abf65fa64dbb5dd654eae1748ec28def09b89a/src/main/resources/functions_grel.ttl#L1091
