### ISSUE TITLE
Function composition in subject URI template

### ISSUE THREAD

**Issue by namedgraph** [RMLio/rmlmapper-java#231]
This YARRRML generates RML in Matey but does not generate any RDF using the default `data.json` with persons:
```yml
prefixes:
 ex: "http://example.com/"
 grel: "http://users.ugent.be/~bjdmeest/function/grel.ttl#"

mappings:
  person:
    sources:
      - ['data.json~jsonpath', '$.persons[*]']
    s:
      function: grel:array_join
      parameters:
        - [ grel:p_array_a, "https://example.org/" ]
        - parameter: grel:p_array_a
            value:
              function: grel:string_md5
              parameters:
                - [ grel:valueParameter, $(firstname)]
    po:
      - [a, foaf:Person]
```
What are we doing wrong?

**Comment by bjdmeest** [comment]
the indentation of `value` was wrong, creating bogus RML, you can try below

```yaml
prefixes:
 ex: "http://example.com/"
 grel: "http://users.ugent.be/~bjdmeest/function/grel.ttl#"

mappings:
  person:
    sources:
      - ['data.json~jsonpath', '$.persons[*]']
    s:
      function: grel:array_join
      parameters:
        - [ grel:p_array_a, "https://example.org/" ]
        - parameter: grel:p_array_a
          value:
            function: grel:string_md5
            parameters:
              - [ grel:valueParameter, $(firstname)]
    po:
      - [a, foaf:Person]
```

**Comment by namedgraph** [comment]
Thank you!

**Comment by namedgraph** [comment]
Hmm.. I tried applying the same logic to `graph` but it does not seem to work:
```yml
    graph:
      function: grel:array_join
      parameters:
        - [ grel:p_array_a, "https://example.org/" ]
        - parameter: grel:p_array_a
            value:
              function: grel:string_md5
              parameters:
                - [ grel:valueParameter, $(firstname)]
```
I get "Could not generate RML rules." in Matey.
