### ISSUE TITLE
`DATAIO_NULL` string in CSV mapping output using 7.0.0

### ISSUE THREAD

**Issue by namedgraph** [RMLio/rmlmapper-java#238]
With the previous version the output was:
```turtle
<https://data.beamery.com/smth/9#this> <http://www.w3.org/2004/02/skos/core#definition> "VP STRATEGIC ACCOUNTS, NA\n\nBeamery \n
***truncated***"@en .
```
With version 7.0.0 the output is:
```turtle
<https://data.beamery.com/smth/9#this> <http://www.w3.org/2004/02/skos/core#definition> "VP STRATEGIC ACCOUNTS, NA\nDATAIO_NULL\nBeamery \n
***truncated***"@en .
```
CSV row looks like this (multiline string value):
```csv
9,"Vice President, N/A Strategic Accounts",9,"VP STRATEGIC ACCOUNTS, NA

Beamery 
***truncated***"
```
YARRML mapping:
```yaml
  Concept:
    sources: smth
    s: smth:$(id)#this
    po:
      ...
      - [ skos:definition, $(role_description), en~lang ]
```
