### ISSUE TITLE
Null function not behaving correctly

### ISSUE THREAD

**Issue by alloka** [RMLio/rmlmapper-java#245]
Hello All,

So I'm trying to use the null function to check the non-existence of a json entity in my data , but it is not behaving correctly:

My data is as follows:
`[{"id":"0","labels":["Student"],"properties":{"id":20}},{"type":"stay","id":"1","labels":["Sport"],"properties":{"sport_id":100,"sport_name":"Tennis"}},{"type":"node","id":"2","labels":["Student"],"properties":{"name":"Venus Williams","id":10,"sport":100}}]`

and my mappings are the following:
prefixes:
  rr: http://www.w3.org/ns/r2rml#
  foaf: http://xmlns.com/foaf/0.1/
  xsd: http://www.w3.org/2001/XMLSchema#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  Airport: http://example.org/Airport/
  ontology: http://data.sfgov.org/ontology/
  grel: http://users.ugent.be/~bjdmeest/function/grel.ttl#
  exfunc: http://example.com/idlab/function/
  ex: http://www.example.org/
  idlab-fn: https://w3id.org/imec/idlab/function#`
  

mappings:
  episode:
    sources:
      - [data.json~jsonpath, "$.[*]"]
    s: ex:$(id)
    condition:
        function: idlab-fn:isNull
        parameters:
            - [grel:valueParameter, $(type)]
    po:
    - p: a
      o: ex:Node
     
The output is: 

`<http://www.example.org/0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.example.org/Node> .
<http://www.example.org/1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.example.org/Node> .
<http://www.example.org/2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.example.org/Node> .`

while the expected output should return only the first triple

Also, is there any way to use the not null function as well in RML?

Best regards,
Ali.

**Comment by bjdmeest** [comment]
Could your paste the RML mapping file and properly format the yarrrml code? hard to bugfix this.

For the not null function: you can nest the not function with the null function, for an example of a nesting in a condition, see https://github.com/RMLio/yarrrml-parser/blob/development/test/condition-on-mapping-nested/mapping.yarrrml

**Comment by alloka** [comment]
Dear Ben,

so I attached both the yaml and mappings file as txt files:

[bug_yaml.txt](https://github.com/user-attachments/files/17748709/bug_yaml.txt)
[mappings.txt](https://github.com/user-attachments/files/17748711/mappings.txt)


Best regards,
Ali.

**Comment by DylanVanAssche** [comment]
> So I'm trying to use the null function to check the non-existence of a json entity in my data

I assume you don't want to get a result when the `type` key does not exist in the JSON, by combining `not` with `isNull`, you can check if the `type` key exists and is not NULL. If that's the case, this mapping works:

**Input**

```
[
   {
      "id":"0",
      "labels":[
         "Student"
      ],
      "properties":{
         "id":20
      }
   },
   {
      "type":"stay",
      "id":"1",
      "labels":[
         "Sport"
      ],
      "properties":{
         "sport_id":100,
         "sport_name":"Tennis"
      }
   },
   {
      "type":"node",
      "id":"2",
      "labels":[
         "Student"
      ],
      "properties":{
         "name":"Venus Williams",
         "id":10,
         "sport":100
      }
   }
]
```

**YARRRML**

```
prefixes:
 ex: "http://example.com/"
 grel: http://users.ugent.be/~bjdmeest/function/grel.ttl#
 idlab-fn: "https://w3id.org/imec/idlab/function#"

mappings:
  person:
    sources:
      - ['data.json~jsonpath', '$.[*]']
    subjects: ex:$(id)
    condition:
      function: grel:boolean_not
      parameters:
        - parameter: grel:bool_b
          value:
            function: idlab-fn:isNull
            parameters:
              - [idlab-fn:str, $(type)]

    po:
      - [a, ex:Node]
```

**Output**

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix ex: <http://example.com/> .
@prefix grel: <http://users.ugent.be/~bjdmeest/function/grel.ttl#> .
@prefix idlab-fn: <https://w3id.org/imec/idlab/function#> .

ex:1 rdf:type ex:Node .

ex:2 rdf:type ex:Node .
```

If you don't want the `not`, you can just use the `isNull` function. You mapping contained a wrong parameter, you need `idlab-fn:str`. You can find them here: https://rml.io/docs/rmlmapper/default-functions/
