### ISSUE TITLE
rr:ParentTriplesMap without join condition not working as described in the specification

### ISSUE THREAD

**Issue by herminiogg** [RMLio/rmlmapper-java#28]
Hi:

I was testing the <#TransportMapping> and the <#StopMapping> provided in the RML specification (http://rml.io/spec.html#example-input-0) and it seems that this implementation is not giving the expected results.

When using the last release of the rmlmapper-java (v4.3.3-r92) the result is the following one:

```
<http://trans.example.com/bus/25> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/ns#Transport>.
<http://trans.example.com/bus/25> <http://example.com/ns#type> <http://trans.example.com/vehicle/SingeDecker>.
<http://trans.example.com/bus/25> <http://example.com/ns#stop> <http://trans.example.com/stop/645>.
<http://trans.example.com/bus/25> <http://example.com/ns#stop> <http://trans.example.com/stop/651>.
<http://trans.example.com/bus/25> <http://example.com/ns#stop> <http://trans.example.com/stop/873>.
<http://trans.example.com/bus/25> <http://example.com/ns#stop> <http://trans.example.com/stop/651>.
<http://trans.example.com/bus/47> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/ns#Transport>.
<http://trans.example.com/bus/47> <http://example.com/ns#type> <http://trans.example.com/vehicle/DoubleDecker>.
<http://trans.example.com/bus/47> <http://example.com/ns#stop> <http://trans.example.com/stop/645>.
<http://trans.example.com/bus/47> <http://example.com/ns#stop> <http://trans.example.com/stop/651>.
<http://trans.example.com/bus/47> <http://example.com/ns#stop> <http://trans.example.com/stop/873>.
<http://trans.example.com/bus/47> <http://example.com/ns#stop> <http://trans.example.com/stop/651>.
<http://trans.example.com/stop/645> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/ns#Stop>.
<http://trans.example.com/stop/645> <http://example.com/ns#stop> "645"^^<http://www.w3.org/2001/XMLSchema#int>.
<http://trans.example.com/stop/645> <http://example.com/ns#stopLabel> "\n        Airport\n      ".
<http://trans.example.com/stop/651> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/ns#Stop>.
<http://trans.example.com/stop/651> <http://example.com/ns#stop> "651"^^<http://www.w3.org/2001/XMLSchema#int>.
<http://trans.example.com/stop/651> <http://example.com/ns#stopLabel> "\n        Conference center\n      ".
<http://trans.example.com/stop/873> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/ns#Stop>.
<http://trans.example.com/stop/873> <http://example.com/ns#stop> "873"^^<http://www.w3.org/2001/XMLSchema#int>.
<http://trans.example.com/stop/873> <http://example.com/ns#stopLabel> "\n        Central Park\n      ".
<http://trans.example.com/stop/651> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/ns#Stop>.
<http://trans.example.com/stop/651> <http://example.com/ns#stop> "651"^^<http://www.w3.org/2001/XMLSchema#int>.
<http://trans.example.com/stop/651> <http://example.com/ns#stopLabel> "\n        Conference center\n      ". 
```

This is not the behaviour described in the specification because it assigns all the stops to all the buses. So, for bus 25 we have stops 873, 645, 651 (twice) and the same stops for bus 47. Whereas, in the XML file, stop 645 is under bus 25, stop 873 under bus 47 and stop 651 under both buses.

However, when using the last release of the legacy implementation (RML-Mapper-v3.0.2) the output with the same RML mapping file and XML file is different and according to the specification.

```
<http://trans.example.com/stop/645> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/ns#Stop> .
<http://trans.example.com/stop/645> <http://example.com/ns#stop> "645"^^<http://www.w3.org/2001/XMLSchema#int> .
<http://trans.example.com/stop/645> <http://example.com/ns#stopLabel> "Airport" .
<http://trans.example.com/stop/651> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/ns#Stop> .
<http://trans.example.com/stop/651> <http://example.com/ns#stop> "651"^^<http://www.w3.org/2001/XMLSchema#int> .
<http://trans.example.com/stop/651> <http://example.com/ns#stopLabel> "Conference center" .
<http://trans.example.com/stop/873> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/ns#Stop> .
<http://trans.example.com/stop/873> <http://example.com/ns#stop> "873"^^<http://www.w3.org/2001/XMLSchema#int> .
<http://trans.example.com/stop/873> <http://example.com/ns#stopLabel> "Central Park" .
<http://trans.example.com/bus/25> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/ns#Transport> . <http://trans.example.com/bus/25> <http://example.com/ns#stop> <http://trans.example.com/stop/645> .
<http://trans.example.com/bus/25> <http://example.com/ns#stop> <http://trans.example.com/stop/651> .
<http://trans.example.com/bus/25> <http://example.com/ns#type> <http://trans.example.com/vehicle/SingeDecker> .
<http://trans.example.com/bus/47> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/ns#Transport> . <http://trans.example.com/bus/47> <http://example.com/ns#stop> <http://trans.example.com/stop/873> .
<http://trans.example.com/bus/47> <http://example.com/ns#stop> <http://trans.example.com/stop/651> .
<http://trans.example.com/bus/47> <http://example.com/ns#type> <http://trans.example.com/vehicle/DoubleDecker> .
```
Reading the Section 7 of the specification (http://rml.io/spec.html#relationships-among-logical-sources-rr-parenttriplesmap-rr-joincondition-rr-child-and-rr-parent), it says that a `joinCondition` is not needed when linking mappings with the same `LogicalSource`. Has this mechanism changed in the new library? Is it now mandatory to provide the `joinCondition`?

**Comment by skontopo** [comment]
Hi there,

I recently started playing around with RML a bit and stumbled upon the exact same problem. Looking forward to seeing how this can be tackled.

**Comment by marioscrock** [comment]
Hi everyone, 
I have a similar problem and I think it is strictly related to that issue and similar to the example in the specification. I tried to come up with an easy example showing it. Let's assume this is the content of the `student.json` file that I want to map to RDF.  
``` json
{
	"students" : [
	{
		"student" : "Steve",
		"courses" : [
		{
			"name" : "Math1",
			"CFU" : "10"
		},
		{
			"name" : "Math2",
			"CFU" : "8"
		}
		]
	},
	{
		"student" : "Paul",
		"courses" : [
		{
			"name" : "InformationTheory",
			"CFU" : "10"
		},
		{
			"name" : "Algorithms1",
			"CFU" : "10"
		}
		]
	}]
}
```
The problem is how can I obtain a result like the one shown below and mapping the nested structure of the json file. 
``` ttl
ex:Steve a ex:Student ;
	ex:name "Steve" ;
	ex:course ex:Course_Math1 ;
	ex:course ex:Course_Math2 .
ex:Steve a ex:Student ;
	ex:name "Paul" ;
	ex:course ex:Course_InformationTheory ;
	ex:course ex:Course_Algorithms1 .
ex:Course_Math1 a ex:Course ;
	ex:name "Math1" ;
	ex:credits "10" ;
ex:Course_Math2 a ex:Course ;
	ex:name "Math2" ;
	ex:credits "8" ;
ex:Course_InformationTheory a ex:Course ;
	ex:name "InformationTheory" ;
	ex:credits "10" ;
ex:Course_Algorithms1 a ex:Course ;
	ex:name "Algorithms1" ;
	ex:credits "10" ;
```
I need two different mappings for students and courses since the subject changes, but I can't find a solution allowing me to map only the right courses to the right student. I think the problem is related to the fact that I cannot express a proper `join condition` since the relation is in the nested structure of the document and I cannot access the parent node from the child once defined the iterator.
``` yaml
prefixes:
  ex: "http://www.example.com#"

mappings:
  students:
    sources:
      - ["data/students.json~jsonpath", "$.students[*]"] 
    s: ex:$(student)
    po:
      - [a, tm:Student]
      - [tm:name, $(student)]
      - p: ex:course
        o:
          - mapping: courses
  courses:
    sources:
      - ["data/students.json~jsonpath", "$.students[*].courses[*]"] 
    s: ex:Course_$(name)
    po:
      - [a, tm:Course]
      - [tm:name, $(name)]
      - [tm:credits, $(credits)]

```
Please let me know if a solution for this problem exists or if this issue is related to the one pointed out in this thread. Thank you.

**Comment by marioscrock** [comment]
A possible solution related to the example above, not using join conditions but exploiting IRIs.
```
prefixes:
  ex: "http://www.example.com#"

mappings:
  students:
    sources:
      - ["data/students.json~jsonpath", "$.students[*]"] 
    s: ex:$(student)
    po:
      - [a, ex:Student]
      - [ex:name, $(student)]
      - [ex:course, "ex:Course_$(courses[*].name)~iri"]

  courses:
    sources:
      - ["data/students.json~jsonpath", "$.students[*].courses[*]"] 
    s: ex:Course_$(name)
    po:
      - [a, ex:Course]
      - [ex:name, $(name)]
      - [ex:credits, $(CFU)]
```
