### ISSUE TITLE
How to use a generated UUID in the subject's URI

### ISSUE THREAD

**Issue by ysghandi** [RMLio/rmlmapper-java#47]
To generate a UUID I have used the code snippet below:

<#UUIDGeneration>
  a rr:TriplesMap;
  rml:logicalSource [
    rml:source "filename.xml" ;
    rml:iterator "/Book";
    rml:referenceFormulation ql:XPath
  ];
  rr:subjectMap [
    fnml:functionValue [
      rr:predicateObjectMap [
        rr:predicate fno:executes ;
        rr:objectMap [ rr:constant grel:random ] ] ;
    ];
    rr:termType rr:IRI
  ];

  rr:predicateObjectMap [
    rr:predicate ex:hasGeneratedUUID;
    rr:objectMap [
      fnml:functionValue [
      	rr:predicateObjectMap [
      		rr:predicate fno:executes ;
      		rr:objectMap [ rr:constant grel:random ] ]
      ]
    ]
  ].

Is there a way that I can assign that generated UUID to the subject's URI e.g.   

  rr:subjectMap [
    rr:template "http://example.com#Book-{generatedURI}";
    rr:class ex:Book
  ];

**Comment by pheyvaer** [comment]
Hi @ysghandi 

Thanks for your question! Functions can also be used in Subject Maps. An example can be found in the [test cases](https://github.com/RMLio/rmlmapper-java/blob/master/src/test/resources/rml-fno-test-cases/RMLFNOTC0005-CSV/mapping.ttl#L23). In your case you will need to combine the function that generates the UUID with a concat function that combines `http://example.com#Book-` with the UUID.

**Comment by ysghandi** [comment]
Hi @pheyvaer ,
Thank you for your reply. Could you please provide me with an example of concat function?

**Comment by pheyvaer** [comment]
In the RMLMapper there is standard [`grel:array_join`](https://github.com/RMLio/rmlmapper-java/blob/master/src/main/resources/functions_grel.ttl#L56) available. You need to add `grel:param_a` for every element that you want to concatenate. In your case that would be `http://example.com#Book-` and the UUID.

**Comment by ysghandi** [comment]
I looked at this test case: https://github.com/RMLio/rmlmapper-java/tree/master/src/test/resources/rml-fno-test-cases/RMLFNOTC0000-CSV but it doesn't contain the grel:array_join example as it was mentioned in its description.
Furthermore, I would like to have the generated UUID to be a part of URI in the subject not as a predicate.
I tried the code below but it doesn't work:
`rr:subjectMap [
rr:template "http://example.com#Book-concat(
{grel:param_a <#UUIDGeneration>}";
rr:class ex:Book
];`

**Comment by pheyvaer** [comment]
The test case I pointed to was https://github.com/RMLio/rmlmapper-java/blob/master/src/test/resources/rml-fno-test-cases/RMLFNOTC0005-CSV/mapping.ttl It shows how to use a function with the Subject Map. For your case you would need to use `grel:array_join` instead.

**Comment by bjdmeest** [comment]
Have a look at the RML document below, which would roughly do what you want:

```ttl
@prefix rr:   <http://www.w3.org/ns/r2rml#> .
@prefix rml:  <http://semweb.mmlab.be/ns/rml#> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ql:   <http://semweb.mmlab.be/ns/ql#> .
@prefix map:  <http://mapping.example.com/> .

map:map_person_0
    rml:logicalSource     map:source_0 ;
    a                     rr:TriplesMap ;
    rdfs:label            "person" ;
    rr:subjectMap         map:s_0 ;
    rr:predicateObjectMap map:pom_2 .

map:source_0
    a                        rml:LogicalSource ;
    rml:source               "student.csv" ;
    rml:referenceFormulation ql:CSV .

map:s_0
    a                                              rr:SubjectMap, <http://semweb.mmlab.be/ns/fnml#FunctionTermMap> ;
    rr:termType                                    rr:IRI ;
    <http://semweb.mmlab.be/ns/fnml#functionValue> map:fn_0 .

map:fn_0
    rml:logicalSource     map:source_0 ;
    rr:predicateObjectMap map:pomexec_0, map:pom_0, map:pom_1 .

map:pomexec_0
    rr:predicateMap map:pmexec_0 ;
    rr:objectMap    map:omexec_0 .

map:pmexec_0
    rr:constant <https://w3id.org/function/ontology#executes> .

map:omexec_0
    rr:constant "http://users.ugent.be/~bjdmeest/function/grel.ttl#array_join" ;
    rr:termType rr:IRI .

map:pom_0
    a               rr:PredicateObjectMap ;
    rr:predicateMap map:pm_0 ;
    rr:objectMap    map:om_0 .

map:pm_0
    a           rr:PredicateMap ;
    rr:constant <http://users.ugent.be/~bjdmeest/function/grel.ttl#p_array_a> .

map:om_0
    a           rr:ObjectMap ;
    rr:constant "http://example.com/person/" ;
    rr:termType rr:Literal .

map:pom_1
    a               rr:PredicateObjectMap ;
    rr:predicateMap map:pm_1 ;
    rr:objectMap    map:om_1 .

map:pm_1
    a           rr:PredicateMap ;
    rr:constant <http://users.ugent.be/~bjdmeest/function/grel.ttl#p_array_a> .

map:om_1
    a                                              rr:ObjectMap, <http://semweb.mmlab.be/ns/fnml#FunctionTermMap> ;
    <http://semweb.mmlab.be/ns/fnml#functionValue> map:fn_1 .

map:fn_1
    rml:logicalSource     map:source_0 ;
    rr:predicateObjectMap map:pomexec_1 .

map:pomexec_1
    rr:predicateMap map:pmexec_1 ;
    rr:objectMap    map:omexec_1 .

map:pmexec_1
    rr:constant <https://w3id.org/function/ontology#executes> .

map:omexec_1
    rr:constant "http://example.com/idlab/function/random" ;
    rr:termType rr:IRI .

map:pom_2
    a               rr:PredicateObjectMap ;
    rr:predicateMap map:pm_2 ;
    rr:objectMap    map:om_2 .

map:pm_2
    a           rr:PredicateMap ;
    rr:constant rdf:type .

map:om_2
    a           rr:ObjectMap ;
    rr:constant "http://example.com/Person" ;
    rr:termType rr:IRI .
```

This was automatically generated from following [YARRRML](https://rml.io/yarrrml/) document using [Matey](https://rml.io/yarrrml/matey/)

```yaml
prefixes:
  ex: "http://example.com/"
  grel: "http://users.ugent.be/~bjdmeest/function/grel.ttl#"
  idlab-fn: "http://example.com/idlab/function/"

mappings:
  person:
    sources:
      - ['student.csv~csv']
    s:
      function: grel:array_join
      parameters:
        - [grel:p_array_a, "http://example.com/person/"]
        - parameter: grel:p_array_a
          value:
            function: idlab-fn:random
            parameters: [] # This is needed atm, bug in the YARRRML parser
    po:
      - [a, ex:Person]
```

**Comment by ysghandi** [comment]
Thank you for your reply @bjdmeest and @pheyvaer 
Is the array_join function defined in grel ns? If so, my editor doesn't suggest this function.

**Comment by ysghandi** [comment]
@pheyvaer and @bjdmeest thank you for your reply. I tried the code snippet below but still, I can't get the arbitrary result.

`rr:subjectMap [

      fnml:functionValue [
        rr:predicateObjectMap [
        rr:predicate fno:executes ;
        rr:objectMap [ rr:constant idlab-fn:random ] ];
        rr:predicateObjectMap [
          rr:predicate grel:array_join;
          rr:objectMap[ rr:template "http://example.com#Book-{@Name}"]
        ]
      ];
         
     rr:class iec61499:Book; 
     rr:termType rr:IRI];`

In the genrated ttl, the combination of the UUID and the base URI is used instead of using the subject URI "http://example.com#Book-{@Name}".
result:
`<http://example.com/example0#ed716cce-54a6-4276-aebf-be0a04c96bf4>
  a ex:Book;`

I also tried concat function and got the same result. It would also be great if you could provide an example of grel:array_join and grel:param_a without using YARRRML.

**Comment by bjdmeest** [comment]
@ysghandi, does that mean that the [RML snippet above](https://github.com/RMLio/rmlmapper-java/issues/47#issuecomment-601734379) doesn't work for you? Because that one uses grel_array_join and grel:p_array_a

**Comment by ysghandi** [comment]
@bjdmeest thank you. I found the mistake that I didn't get the arbitrary result. I used
`map:om_2
    a           rr:ObjectMap ;
    rr:class ex:Book ;
    rr:termType rr:IRI .`
now it is working using `rr:template` instead of `rr:class` .

**Comment by Myasir92** [comment]
I am facing same issue as i want to generate uuid as template of subjectmap but unable to use it even i create a function which generate UUID but unable to use that function in rr:template so can you please help me. Following code i have 

@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rml: <http://semweb.mmlab.be/ns/rml#> .
@prefix prefix: <http://mytestprefix.org/> .
@prefix ql: <http://semweb.mmlab.be/ns/ql#> .
@prefix fnml: <http://semweb.mmlab.be/ns/fnml#> .
@prefix fno: <http://w3id.org/function/ontology#> .
@prefix sti: <http://sti2.at#> .
@prefix grel: <http://users.ugent.be/~bjdmeest/function/grel.ttl#> .
@base <http://sti2.at/> . #the base for the classes


<#LOGICALSOURCE>
rml:source "./input.json";
rml:referenceFormulation ql:JSONPath;
rml:iterator "$.*".


<#Mapping>
rml:logicalSource <#LOGICALSOURCE>;

 rr:subjectMap [
     rr:template "http://enapso.org/test#Person-concat({grel:array_join <#FunctionMap>})";
    rr:class prefix:Person ;
 ];


rr:predicateObjectMap [
    rr:predicate prefix:name;
    rr:objectMap [ rml:reference "name" ];
];

rr:predicateObjectMap [
    rr:predicate prefix:age;
    rr:objectMap <#FunctionMap>;
].

 <#FunctionMap>
     fnml:functionValue [
         rml:logicalSource <#LOGICALSOURCE> ;
         rr:predicateObjectMap [
             rr:predicate fno:executes ;
             rr:objectMap[ sti:jsFunction " ( function create_UUID(){      var dt = new Date().getTime(); var uuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {   var r = (dt + Math.random()*16)%16 | 0;     dt = Math.floor(dt/16);   return (c=='x' ? r :(r&0x3|0x8)).toString(16);    }); return uuid;})" ] #
] ;
         rr:predicateObjectMap [
             rr:predicate grel:str ;
             rr:objectMap [ rml:reference "url" ]
         ];
     ] .

**Comment by bjdmeest** [comment]
> 
> 
> @bjdmeest thank you. I found the mistake that I didn't get the arbitrary result. I used
> `map:om_2 a rr:ObjectMap ; rr:class ex:Book ; rr:termType rr:IRI .`
> now it is working using `rr:template` instead of `rr:class` .
> 
> Is there any example like the code snippet above in RML, not YARRRML?

@ysghandi the first code snippet of [my comment](https://github.com/RMLio/rmlmapper-java/issues/47#issuecomment-601734379) is the RML equivalent of the YARRRML snippet :)

**Comment by bjdmeest** [comment]
@CyberDaedalus00 Please note that the RML of https://github.com/RMLio/rmlmapper-java/issues/47#issuecomment-606277030 won't give you the result you need, Please see the snippet below:

```turtle
@prefix ql: <http://semweb.mmlab.be/ns/ql#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix rml: <http://semweb.mmlab.be/ns/rml#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

@prefix fnml: <http://semweb.mmlab.be/ns/fnml#> .
@prefix fno: <https://w3id.org/function/ontology#> .
@prefix idlab-fn: <http://example.com/idlab/function/> .
@prefix grel: <http://users.ugent.be/~bjdmeest/function/grel.ttl#> .

@prefix stix: <http://docs.oasis-open.org/cti/ns/stix#> .
@prefix stixCore: <http://docs.oasis-open/cti/ns/stix/core#> .

@base <http://docs.oasis-open.org/cti/ns/stix#> .

<http://docs.oasis-open.org/cti/ns/map#ExternalReferenceMapping>
a rr:TriplesMap ;

rml:logicalSource [
    rml:source "stix-document.json" ;
    rml:referenceFormulation ql:JSONPath ;
    rml:iterator "$.objects[*]" ;
] ;
rr:subjectMap [
    fnml:functionValue [
        rr:predicateObjectMap [
            rr:predicate fno:executes ;
            rr:objectMap [ rr:constant grel:array_join ] 
        ];
        rr:predicateObjectMap [
            rr:predicate grel:p_array_a ;
            rr:objectMap [ rr:constant "external-reference--" ] # You don't need to include the _b:
        ];
        rr:predicateObjectMap [
            rr:predicate grel:p_array_a ;
            rr:objectMap [
                fnml:functionValue [
                    rr:predicateObjectMap [
                        rr:predicate fno:executes ;
                        rr:objectMap [ rr:constant idlab-fn:random ]  # The random function is nested in the `grel:array_join` function
                    ]
				]
            ]
        ];
    ] ;
    rr:class stixCore:ExternalReference ;
    rr:termType rr:BlankNode; # You do need to set the termType of the subject to BlankNode
] ;

rr:predicateObjectMap [
    rr:predicate stixCore:source_name ;
    rr:objectMap [ rml:reference "source_name" ]
] ;

.

```

**Comment by CyberDaedalus00** [comment]
This worked exactly as advertised.  The change you described made a LOT of sense, so thank you very much!

**Comment by nsveli** [comment]
> @CyberDaedalus00 Please note that the RML of [#47 (comment)](https://github.com/RMLio/rmlmapper-java/issues/47#issuecomment-606277030) won't give you the result you need, Please see the snippet below:
> 
> ```turtle
> @prefix ql: <http://semweb.mmlab.be/ns/ql#> .
> @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
> @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
> @prefix rr: <http://www.w3.org/ns/r2rml#> .
> @prefix rml: <http://semweb.mmlab.be/ns/rml#> .
> @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
> 
> @prefix fnml: <http://semweb.mmlab.be/ns/fnml#> .
> @prefix fno: <https://w3id.org/function/ontology#> .
> @prefix idlab-fn: <http://example.com/idlab/function/> .
> @prefix grel: <http://users.ugent.be/~bjdmeest/function/grel.ttl#> .
> 
> @prefix stix: <http://docs.oasis-open.org/cti/ns/stix#> .
> @prefix stixCore: <http://docs.oasis-open/cti/ns/stix/core#> .
> 
> @base <http://docs.oasis-open.org/cti/ns/stix#> .
> 
> <http://docs.oasis-open.org/cti/ns/map#ExternalReferenceMapping>
> a rr:TriplesMap ;
> 
> rml:logicalSource [
>     rml:source "stix-document.json" ;
>     rml:referenceFormulation ql:JSONPath ;
>     rml:iterator "$.objects[*]" ;
> ] ;
> rr:subjectMap [
>     fnml:functionValue [
>         rr:predicateObjectMap [
>             rr:predicate fno:executes ;
>             rr:objectMap [ rr:constant grel:array_join ] 
>         ];
>         rr:predicateObjectMap [
>             rr:predicate grel:p_array_a ;
>             rr:objectMap [ rr:constant "external-reference--" ] # You don't need to include the _b:
>         ];
>         rr:predicateObjectMap [
>             rr:predicate grel:p_array_a ;
>             rr:objectMap [
>                 fnml:functionValue [
>                     rr:predicateObjectMap [
>                         rr:predicate fno:executes ;
>                         rr:objectMap [ rr:constant idlab-fn:random ]  # The random function is nested in the `grel:array_join` function
>                     ]
> 				]
>             ]
>         ];
>     ] ;
>     rr:class stixCore:ExternalReference ;
>     rr:termType rr:BlankNode; # You do need to set the termType of the subject to BlankNode
> ] ;
> 
> rr:predicateObjectMap [
>     rr:predicate stixCore:source_name ;
>     rr:objectMap [ rml:reference "source_name" ]
> ] ;
> 
> .
> ```

Hi, I was wondering if there is any way to achieve similar output, but for with a random function but for IRI instead of BlankNode.

Thank you in advance!

**Comment by namedgraph** [comment]
@pheyvaer I'm trying to use your [example]() as object value:
```yaml
mappings:
  Person:
    sources: Person
    graph: persons:$(id)
    s: persons:$(id)#this
    po:
      - p: foaf:based_near
      - o:
          function: grel:array_join
          parameters:
            - [grel:p_array_a, "http://example.com/person/"]
            - parameter: grel:p_array_a
              value:
                function: fn:random
                parameters: [] # This is needed atm, bug in the YARRRML parser
```
But I'm getting an error:
```
mapping "Person": po with predicate(s) "foaf:based_near" does not have an object defined. Skipping.
TypeError: Cannot read properties of undefined (reading 'forEach')
    at /opt/homebrew/lib/node_modules/@rmlio/yarrrml-parser/lib/abstract-generator.js:251:23
    at Array.forEach (<anonymous>)
    at RMLGenerator.generateMapping (/opt/homebrew/lib/node_modules/@rmlio/yarrrml-parser/lib/abstract-generator.js:212:32)
    at RMLGenerator.generateMapping (/opt/homebrew/lib/node_modules/@rmlio/yarrrml-parser/lib/rml-generator.js:199:11)
    at /opt/homebrew/lib/node_modules/@rmlio/yarrrml-parser/lib/rml-generator.js:165:16
    at Array.forEach (<anonymous>)
    at /opt/homebrew/lib/node_modules/@rmlio/yarrrml-parser/lib/rml-generator.js:147:25
    at Array.forEach (<anonymous>)
    at RMLGenerator.convertExpandedJSON (/opt/homebrew/lib/node_modules/@rmlio/yarrrml-parser/lib/rml-generator.js:57:35)
    at RMLGenerator.convert (/opt/homebrew/lib/node_modules/@rmlio/yarrrml-parser/lib/abstract-generator.js:81:17)
```
```

**Comment by pheyvaer** [comment]
The issue is with
```yaml
      - p: foaf:based_near
      - o:
```
It should be without the second `-`:

```yaml
      - p: foaf:based_near
        o:
```

**Comment by namedgraph** [comment]
Right, my bad. But it doesn't seem to make a difference in the output -- it's as if `fn:random` has no effect:
```
  Person:
    sources: Person
    graph: persons:$(id)
    s: persons:$(id)#this
    po:
      - [ a, beam:Person ]
      - [ dcterms:identifier, $(id) ]
      - [ foaf:gender, $(gender) ]
      - p: foaf:based_near
        o:
          function: grel:array_join
          parameters:
            - [grel:p_array_a, "http://example.com/person/"]
            - parameter: grel:p_array_a
              value:
                function: fn:random
                parameters: [] # This is needed atm, bug in the YARRRML parser
```
Output:
```
<https://data.beamery.com/persons/IO2AxmvOt7x2k5alM2sW8g_0000#this> <http://xmlns.com/foaf/0.1/based_near> "http://example.com/person/"  <https://data.beamery.com/persons/IO2AxmvOt7x2k5alM2sW8g_0000>.
```

**Comment by bjdmeest** [comment]
@namedgraph I assume you're using the right prefixes? Because the YARRRML below works on the online demo at https://rml.io/yarrrml/matey/

```yaml
prefixes:
 ex: "http://example.com/"
 persons: "http://example.com/persons/"
 fn: "http://example.com/idlab/function/"
 grel: "http://users.ugent.be/~bjdmeest/function/grel.ttl#"

mappings:
  person:
    sources:
      - ['data.json~jsonpath', '$.persons[*]']
    # graph: persons:$(firstname)
    s: persons:$(firstname)#this
    po:
      - p: foaf:based_near
        o:
          function: grel:array_join
          parameters:
            - [grel:p_array_a, "http://example.com/person/"]
            - parameter: grel:p_array_a
              value:
                function: fn:random
                parameters: [] # This is needed atm, bug in the YARRRML parser
```
